### ISSUE TITLE
登录账号

### ISSUE THREAD

**Issue by Ning-Jun** [zzayne/iview-dynamicRouter#1]
登录账号没有加以区分啊

**Comment by zzayne** [comment]
这个demo目前是读取json里的路由配置数据进行逻辑演示，实际运用的话，需要服务端提供路由数据的接口，然后用户登陆后凭借token进行请求，服务端根据token识别用户身份并返回相应的路由数据，前端用的是这个真实数据来加载动态路由，处理逻辑不变。

**Comment by comkis** [comment]
老哥，讲道理，你这个也太难受了，我把项目搬过去或者把这个里面的文件搬过来都不行，这webpack配置差异那么大不好吧。标准方案不是cli吗。或者说在你这个脚手架之上重新搭建起来？

**Comment by zzayne** [comment]
大兄弟，我开头就写了撒，是基于iview-admin的template分支做的demo，你的项目用不了代码应该是动态import组件的原因吧，那你看下我这个项目最开始版本的提交，用的不是import的方法，基本不用改webpack。或者看一下我引用的那系列博文，应该也能帮到你。
