### ISSUE TITLE
左侧菜单导航问题

### ISSUE THREAD

**Issue by MrBaiYinL** [zzayne/iview-dynamicRouter#11]
老大，根据您的权限验证，左侧的导航栏 是由 后台传递过来的吗？还是后台传递的数据 与我们写好的 进行匹配

**Comment by zzayne** [comment]
我这个项目是菜单和权限都是后台传递的，没使用匹配的方法。

**Comment by MrBaiYinL** [comment]
您好，在登录成功跳转到主页后，menu.json的数据是怎么push进主页的左侧菜单栏的呢？我没有找到这个方法

**Comment by MrBaiYinL** [comment]
找到了，不用回复了，非常感谢

**Comment by zzayne** [comment]
👌

**Comment by MrBaiYinL** [comment]
您好，我在引入menuList的时候，不知道什么原因 刷新了两次，第一次是一个数组，马上进行第二次刷新 变为undified  从而导致报错，Invalid prop: type check failed for prop "menuList". Expected Array, got Undefined.  找不到找了好久无法确定原因在哪里，您可以帮助一下吗？非常感谢

**Comment by zzayne** [comment]
是你自己的项目吗，方便的话，贴下代码或者给个项目demo吧，不然没办法找问题。邮件联系我就好。

**Comment by MrBaiYinL** [comment]
嗯嗯  项目的demo已经邮件发给您了 名称为newProject

**Comment by MrBaiYinL** [comment]
`// 模拟异步请求menuList.json
    let seIdq = sessionStorage.getItem('objStr');
    util.ajax({
        method: "post",
        url: "http://172.16.72.183:8089/index",
        data: {
            authorization: seIdq
        },
        transformRequest: [function(data) {
            let ret = ''
            for (let it in data) {
                ret += encodeURIComponent(it) + '=' + encodeURIComponent(data[it]) + '&'
            }
            return ret
        }],
    }).then(res => {
        console.log(res);
        debugger
        var menuData = res.data;
        util.initRouterNode(constRoutes, menuData);
        util.initRouterNode(otherRoutes, otherRouter);
        // 添加主界面路由
        vm.$store.commit('updateAppRouter', constRoutes.filter(item => item.children.length > 0));
        // 添加全局路由
        vm.$store.commit('updateDefaultRouter', otherRoutes);
        // 刷新界面菜单
        vm.$store.commit('updateMenulist', constRoutes.filter(item => item.children.length > 0));

        let tagsList = [];

        vm.$store.state.app.routers.map((item) => {
            if (item.children.length <= 1) {
                tagsList.push(item.children[0]);
            } else {
                tagsList.push(...item.children);
            }
        });
        vm.$store.commit('setTagsList', tagsList);
    });`
在登录页面加载的时候 这个请求就执行了（登录前） 是什么原因啊？他是不是应该是在登录成功之后，跳转页面之后再请求

**Comment by MrBaiYinL** [comment]
您好，在 util文件里生成路由的 这部分 不知道为什么 在登录前就已经执行了；我不知道是什么原因，该怎么解决，是computed里执行的原因还是别的原因,麻烦大佬指导下，非常感谢

**Comment by zzayne** [comment]
每次刷新的时候，vuex的数据会消失，所以在main.jg的mounted函数里，进行一次路由生成，如果是登录页，自然会在页面加载时登录前请求一次。如果业务需要，可以在登录后把路由数据缓存进localstorage，刷新时从缓存中取也行。

**Comment by MrBaiYinL** [comment]
现在有一个问题就是，我在util中动态请求的时候util.initRouter 方法中把menu.json换成后台接口的时候，这个方法就不调用了 是什么原因啊？

**Comment by MrBaiYinL** [comment]
您好，可以帮助调试一下吗？卡在这里好久了，如果打扰到您的时间，可以有偿，非常感谢

**Comment by MrBaiYinL** [comment]
如果方便麻烦加下我的qq:1019369380;非常感谢
