### ISSUE TITLE
按照你的方法设置之后，进入后台一个页面之后，刷新会直接404，请问下这个怎么解决。

### ISSUE THREAD

**Issue by zouhuigang** [zzayne/iview-dynamicRouter#2]

**Comment by zzayne** [comment]
404页面路由是和后台动态路由一起异步加载的吗

**Comment by zouhuigang** [comment]
不是，是在router.js里面定义的，我把它注释掉了就好了。

> export const routers = [
    loginRouter,
    otherRouter,
    preview,
    locking,
    ...appRouter,
     /* page500,
    page403,
    page404 */
];

**Comment by dingfeipeng** [comment]
按照你的方法报这个错误Errors while compiling. Reload prevented.

**Comment by zouhuigang** [comment]
@dingfeipeng 先加载业务的路由，再加载404路由。
