### ISSUE TITLE
动态路由

### ISSUE THREAD

**Issue by dingfeipeng** [zzayne/iview-dynamicRouter#3]
当设置好动态路由之后就报错```
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/tables/components/multiPageTable.vue
Module not found: Error: Can't resolve './editableTable.vue' in 'C:\Users\ding\Desktop\CustomerSanagementSystem\src\views\tables\components'
@ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/tables/components/multiPageTable.vue 7:21-51
@ ./src/views/tables/components/multiPageTable.vue
@ ./src/views lazy ^./.*.vue$
@ ./src/libs/lazyLoading.js
@ ./src/libs/util.js
@ ./src/main.js
@ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server @/main
Child html-webpack-plugin for "..\index.html":`

**Comment by zzayne** [comment]
应该是你组件的路径写的不对，报错信息里面写了。

**Comment by MrHuang123** [comment]
解决了吗，我也是报这个错

**Comment by dingfeipeng** [comment]
@MrHuang123 我重写了下，就解决了

**Comment by dingfeipeng** [comment]
@zzayne 谢谢

**Comment by zzayne** [comment]
@dingfeipeng 不客气。

**Comment by zzayne** [comment]
@MrHuang123 你的问题应该也是类似的，可能是动态组件的路径问题。
