### ISSUE TITLE
import 动态导入需要安装插件吗？

### ISSUE THREAD

**Issue by Sessionh** [zzayne/iview-dynamicRouter#5]
export default (url) =>()=>import(`@/views/${url}.vue`) 
这句需要装什么插件吗？ 我在vue-cli 项目中使用 报错， 所以问下 ，麻烦解答一下， 谢谢

**Comment by zzayne** [comment]
vue-cli项目是新的吗，看一下你的`babelrc`文件里面是不是和这个项目的一致，动态导入插件在旧的vue-cli版本上需要自己设置。

**Comment by Sessionh** [comment]
谢谢 ，问题解决了 我的vue-cli 项目 需要去掉{} 
export default(url) => resolve => require([`@/components/${url}.vue`], resolve) 
我的vue版本 是2.5.2
